### ISSUE TITLE
camera enumeration

### ISSUE THREAD

**Issue by idelsink** [derpicated/articated_research#2]
Request a list of all the cameras including ID for opencv.

The curent `acquisition::cam_count()` will give the total connected cams.
This will throw a lot of highgui warnings.... For this reason I want the Qt implementation.

http://doc.qt.io/qt-5/cameraoverview.html

**Comment by idelsink** [comment]
This moment the `cam_count()` function of the `acquisition` class is just a stub that will return `10`. This because opencv has some struggles.....

**Comment by Mercotui** [comment]
i fixed this back in 8e917c68128bec192493f4b0f955ea705fd968a5, by using QT's camera enumeration, but I implemented that in the ARticated app, the acquisition code isnt changed. Still, as there is no need for this to be fixed anymore, closing this bug
